### ISSUE TITLE
Architecture could not be deduced from ... arm64

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/boot-utils#98]
While bisecting configs in https://github.com/ClangBuiltLinux/linux/issues/1837, sometimes the machine would fail to boot
```
$ /android1/boot-utils/boot-qemu.py -k .                                                                                         
Traceback (most recent call last):
  File "/android1/boot-utils/boot-qemu.py", line 794, in <module>
    arch = guess_arch(kernel_location)
  File "/android1/boot-utils/boot-qemu.py", line 726, in guess_arch
    raise RuntimeError(
RuntimeError: Architecture could not be deduced from '/android0/kernel-stable/vmlinux: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, BuildID[xxHash]=759cf502547e43dc, with debug_info, not stripped', please explicitly specify it via '-a' or add support for it to guess_arch()!
$ file vmlinux
vmlinux: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, BuildID[xxHash]=759cf502547e43dc, with debug_info, not stripped
```

**Comment by nathanchance** [comment]
Ah, we need to add the non-`pie` strings to `file_rosetta` (I am guessing `CONFIG_RELOCATABLE` is getting flipped?)
